# Generated by Django 4.0.3 on 2022-04-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_order',
            old_name='date',
            new_name='renting_date',
        ),
    ]
