# Generated by Django 4.0.3 on 2022-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
