# Generated by Django 4.0.3 on 2022-05-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_mobile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='renting_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='My_Order',
        ),
    ]
