# Generated by Django 4.0.3 on 2022-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_car_cart_quantity_cart_renting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='renting_date',
            field=models.DateField(),
        ),
    ]
