# Generated by Django 4.0.3 on 2022-05-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cart_renting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='ordered_date',
        ),
    ]
