# Generated by Django 4.0.3 on 2022-05-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='ordered_date',
        ),
    ]
