# Generated by Django 4.0.3 on 2022-05-19 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='My_Orders',
        ),
    ]
